basePath: /api/v1
definitions:
  dto.ResponseHTTP:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.SubscriberInput:
    properties:
      apiaryId:
        type: string
      hiveId:
        type: string
    type: object
  dto.SubscriberOutput:
    properties:
      apiaryId:
        type: string
      createdAt:
        type: string
      hiveId:
        type: string
    type: object
info:
  contact:
    email: vnareiko.lt@gmail.com
    name: Viktor Nareiko
  description: This is an API for Worker Module
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: BeesBuddy worker
  version: "1.0"
paths:
  /settings/subscribers:
    get:
      description: Get subscribers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.SubscriberOutput'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/dto.ResponseHTTP'
      security:
      - ApiKeyAuth: []
      summary: Get active subscribers
      tags:
      - settings
    post:
      description: Create a subscriber
      parameters:
      - description: Subscriber
        in: body
        name: dto.SubscriberInput
        required: true
        schema:
          $ref: '#/definitions/dto.SubscriberInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.SubscriberOutput'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/dto.ResponseHTTP'
      security:
      - ApiKeyAuth: []
      summary: Create a new subscriber
      tags:
      - settings
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
